# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_NAME = "generic/arch"
VM_HOSTNAME = "ansible-roles-test"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME
  config.vm.hostname = VM_HOSTNAME

  config.vm.provider "virtualbox" do |vb|
    vb.name = VM_HOSTNAME
    vb.gui = false
    vb.cpus = 2
    vb.memory = 2048
  end

  ## Arch does not ship with python by default
  config.vm.provision "shell", inline: <<-SHELL
    pacman -Syu --noconfirm # Update system
    pacman -Sy --noconfirm # Update package database
    pacman -S python --noconfirm
    pacman -S which --noconfirm
    pacman -S fastfetch --noconfirm
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/playbook.yml"
    ansible.groups = {
      "system_under_test" => ["default"]
    }
    ansible.host_vars = {
      "default" => {
        "ansible_user" => "vagrant",
        "ansible_python_interpreter" => "/usr/bin/python"
      }
    }
    ansible.extra_vars = {
      "ps1" => '${debian_chroot:+($debian_chroot)}\[\033[01;33m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $ '
    }
  end
end
