# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_NAME = "generic/arch"
VM_HOSTNAME = "ansible-roles-test"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME
  config.vm.hostname = VM_HOSTNAME

  config.vm.provider "virtualbox" do |vb|
    vb.name = VM_HOSTNAME
    vb.gui = false
    vb.cpus = 2
    vb.memory = 2048
  end

  ## Update Arch as an initial step
  ## On real machines this is done via Ansible
  ## Install python as well (needed for Ansible)
  config.vm.provision "shell", inline: <<-SHELL
    pacman -Sy archlinux-keyring --noconfirm
    pacman -Syu --noconfirm # Update system and package database
    pacman -S python --noconfirm
    # pacman -S which --noconfirm # TODO move to ansible
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible-playbook.yml"
    # ansible.verbose = "vvv"
    ansible.groups = {
      "system_under_test" => ["default"]
    }
    ansible.host_vars = {
      "default" => {
        "ansible_user" => "vagrant",
        "ansible_python_interpreter" => "/usr/bin/python",
      }
    }
    ansible.extra_vars = {
      "ps1" => '${debian_chroot:+($debian_chroot)}\[\033[01;33m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $ ',
      "architecture" => "amd64",

      "github" => "git@github.com",
      "dir_work" => "/home/{{ ansible_user }}/work",
      "dir_repos" => "{{ dir_work }}/repos",
      "dir_repos_sommerfeld_io" => "{{ dir_repos }}/sommerfeld-io",
      "dir_repos_sommerfeld_io_archive" => "{{ dir_repos }}/sommerfeld-io-archive",
      "dir_repos_sebastian_sommerfeld_io" => "{{ dir_repos }}/sebastian-sommerfeld-io",
      "docker_stacks_dir" => "/home/{{ ansible_user }}/.docker-stacks",
    }
  end
end
